# Generated by Django 6.0.3 on 2026-04-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product_default.png', null=True, upload_to=''),
        ),
    ]
