# Generated by Django 6.0.3 on 2026-04-24 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='message',
            new_name='text',
        ),
    ]
